include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: true # false
    implicit-dynamic: true # false
linter:
  rules:
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    prefer_single_quotes: true
    prefer_initializing_formals: false # might come in handy to re-enable in the future